corona_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingPage.urls')),
    path('music/', include('feature_dion.urls')),
    path('movies/', include('feature_ajah.urls', namespace="movies")),
    path('health/', include('feature_nathan.urls')),
    path('events/', include('feature_aaya.urls', namespace="events")),
    path('activities/', include('feature_mirsa.urls')),
]

feature_nathan/urls.py
from django.urls import path
from . import views

app_name = 'feature_nathan'
urlpatterns = [
    path('', views.index, name="index"),
    path('isiform/', views.inputform, name='inputform'),
    path('mintaresep/', views.mintaresep, name='mintaresep'),
    path('resep/', views.create_post, name='create'),

]

feature_nathan/models.py
from django.db import models


class resep(models.Model):
    nama = models.CharField(max_length=120, null=True)
    bahan = models.CharField(max_length=700, null=True)
    alat = models.CharField(max_length=700, null=True)
    langkah = models.CharField(max_length=1500, null=True)

class Post(models.Model):
    title = models.CharField(max_length=50)
    bahan = models.CharField(max_length=700, null=True)
    alat = models.CharField(max_length=700, null=True)
    langkah = models.CharField(max_length=1500, null=True)

    def __str__(self):
        return self.title

# Create your models here.

feature_nathan/forms.py
from django import forms
from .models import resep


class buatresep(forms.Form):
    nama = forms.CharField(
        label="Nama",
        max_length=120,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'required': True,
                'style': 'margin-bottom: 4%; margin-top: 2%;',
                'size': '40'
            }
        )
    )
    bahan = forms.CharField(
        label="bahan",
        max_length=700,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'required': True,
                'style': 'margin-bottom: 4%; margin-top: 2%;',
                'size': '40'
            }
        )
    )
    alat = forms.CharField(
        label="alat",
        max_length=700,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'required': True,
                'style': 'margin-bottom: 4%; margin-top: 2%;',
                'size': '40'
            }
        )
    )
    langkah = forms.CharField(
        label="langkah",
        max_length=1500,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'required': True,
                'style': 'margin-bottom: 4%; margin-top: 2%;',
                'size': '40'
            }
        )
    )

feature_nathan/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import JsonResponse
from .models import resep,Post
from .forms import buatresep
from django.contrib.auth.decorators import login_required

@login_required(login_url="landingPage:signin") 
def index(request):
    return render(request, "health.html")

@login_required(login_url="landingPage:signin") 
def inputform(request):
    kumpulanresep = resep.objects.all()
    response = {
        'reseps': kumpulanresep
    }
    return render(request, "isidong.html", response)
# Create your views here.

@login_required(login_url="landingPage:signin") 
def mintaresep(request):
    form = buatresep()
    if request.method == 'POST':
        form = buatresep(request.POST)

        resep.objects.create(
            nama=request.POST['nama'],
            bahan=request.POST['bahan'],
            alat=request.POST['alat'],
            langkah=request.POST['langkah'],

        )

        return HttpResponseRedirect('/health/isiform')

    response = {
        'form': form
    }
    return render(request, "request.html", response)

def create_post(request):
    posts = Post.objects.all()
    response_data = {}

    if request.POST.get('action') == 'post':
        title = request.POST.get('title')
        bahan= request.POST.get('bahan')
        alat= request.POST.get('alat')
        langkah=request.POST.get('langkah')

        response_data['title'] = title
        response_data['bahan'] = bahan
        response_data['alat'] = alat
        response_data['langkah'] = langkah
      
        Post.objects.create(
            title = title,
            bahan = bahan,
            alat = alat,
            langkah = langkah
            )
        return JsonResponse(response_data)

    return render(request, 'resep.html', {'posts':posts}) 

feature_nathan/templates/isidong.html
{% extends 'base.html' %}{% load static %}

{% block title %} Now What | Health {% endblock title %}

{% block content %}

<head>
<link    
rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
/>
<link href="{% static 'css/aos.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'landing_css/main.css'%}" rel="stylesheet" />
    <link href="{% static 'landing_css/styledBase.css' %}" rel="stylesheet" />

</head>

<div style="font-family: poppins; color: #0A5687; font-size: 45px; text-align: center; margin-top : 8%"><b>Resep dari Pengunjung</b></div>
<div class="content container">
    <div class="row">
        <div class="col-md">
<table class="table table-dark" style="margin-top: 10%;">
    <thead style="background-color: #0A5687; color: #ffffff;">
        <tr align="left">
            <th scope = "col">Nama Masakan</th>
            <th scope = "col">Bahan-bahan</th>
            <th scope = "col">Alat</th>
            <th scope = "col">Langkah-langkah</th>
        </tr>
    </thead>
    <tbody style="background-color: #ffffff;">
        {% for i in reseps %}
        <tr>
            <td>{{i.nama}}</td>
            <td>{{i.bahan}}</td>
            <td>{{i.alat}}</td>
            <td>{{i.langkah}}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  <a href="/health/mintaresep">  <button type="sumbit" class="btn btn-warning btn-lg" style="background-color: #F2954E; margin-left: 40%; border-radius: 12%; margin-bottom: 10%;  margin-top: 3%;">Tambah Resep</button> </a>
 
</div>
</div>
</div>

{% endblock %}

feature_nathan/templates/request.html
{% extends 'base.html' %}{% load static %}

{% block title %} Now What | Health {% endblock title %}

{% block content %}
<h1 style="font-family: poppins; font-size: 50px; color:  #0A5687; text-align: center; margin-top: 10%; margin-bottom: 5%;"><b>Bagikan Resep Makananmu!</b></h1>
<form
action="{% url 'feature_nathan:mintaresep' %}"
method="POST">
    {% csrf_token %}

  </div>
  <div class="row font2" style="margin-top: 5; margin-bottom: 5%;">
      <div class="col-sm-5">
          <div class="container" style="display: flex; justify-content: center; align-items: center;">
              <div class="flex">
                  <form method="POST">
                      {% csrf_token %}
                      <div class="form-group">
                          <div class="text-sm">
                            <label for="formGroupExampleInput" style="font-family: poppins; font-size: 15px; color:  #0A5687; align-items: center;"><b><center>Nama masakan:</center></b></label>
                          </div>
                          {{form.nama}}
                      </div>
                      <div class="form-group">
                          <div class="text-sm">
                            <label for="formGroupExampleInput" style="font-family: poppins; font-size: 15px; color:  #0A5687;align-content:  center;"><b><center>Bahan-bahan:</center></b></label>
                          </div>
                          {{form.bahan}}
                      </div>
                      <div class="form-group">
                        <div class="text-sm">
                          <label for="formGroupExampleInput" style="font-family: poppins; font-size: 15px; color:  #0A5687; text-align: center;"><b><center>Alat:</center></b></label>
                        </div>
                        {{form.alat}}
                      </div>
                    <div class="form-group">
                        <div class="text-sm">
                          <label for="formGroupExampleInput" style="font-family: poppins; font-size: 15px; color:  #0A5687; text-align: center; "><b><center>Langkah-langkah:</center></b></label>
                        </div>
                        {{form.langkah}}
                    </div>
                    <button type="submit" class="btn btn-warning" style="background-color: #F2954E; margin-left: 40%; border-radius: 12%;">Bagikan</button>
              </div>
          </div>
      </div>

</form>
    {{reseps}}
{% endblock %}

feature_nathan/templates/resep.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <div class="container pt-5">
            <form method="POST" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <center><label for="exampleInputEmail1" style="font-weight: bold; font-family: poppins; font-size: 15px; color:  #0A5687; align-items: center;">Nama makanan</label></center>
               <input type="text" class="form-control" id="title" placeholder="Title">
                </div>
                <div class="form-group">
                    <center><label for="exampleInputEmail1" style="font-weight: bold; font-family: poppins; font-size: 15px; color:  #0A5687; align-items: center;">Bahan</label> </center>
                    <textarea class="form-control" id="bahan" placeholder="Bahan"></textarea>
                </div>
                <div class="form-group">
                    <center><label for="exampleInputEmail1" style="font-weight: bold; font-family: poppins; font-size: 15px; color:  #0A5687; align-items: center;">Alat</label> </center>
                    <textarea class="form-control" id="alat" placeholder="Alat"></textarea>
                 </div>
                 <div class="form-group">
                    <center><label for="exampleInputEmail1" style="font-weight: bold; font-family: poppins; font-size: 15px; color:  #0A5687; align-items: center;">Langkah</label> </center>
                    <textarea class="form-control" id="langkah" placeholder="Langkah"></textarea>
                </div>
                <center><button  style="border-radius:500px;  background-color: #F2954E;
                border: none;
                color: white;
                padding: 20px;
                padding-left: 40px;
                padding-right: 40px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                margin-bottom: 10%;"type="submit" class="btn btn-primary">Submit</button></center>
                <h1 style="font-weight: bold; font-family: poppins; font-size: 35px; color:  #0A5687; align-items: center; margin-left: 35%;">Kumpulan Resep </h1>
            </form>
            <div class="row mb-2 posts">
                    {% for post in posts %}
                    <div class="col-md-6">
                        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div class="col p-4 d-flex flex-column position-static">
                                <h3 class="mb-0" style="color:  #0A5687">{{post.title}}</h3>
                                <p style="font-weight: bold;">Alat:</p>
                                <p style="white-space: pre-wrap;" class="mb-auto">{{post.alat}}</p>
                                <hr>
                                <p style="font-weight: bold;">Bahan:</p>
                                <p  style="white-space: pre-wrap;" class="mb-auto">{{post.bahan}}</p>
                                <hr>
                                <p style="font-weight: bold;">Langkah-langkah:</p>
                                <p  style="white-space: pre-wrap;" class="mb-auto">{{post.langkah}}</p>
                                <hr>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    
            </div>
        </div>

    </body>
    
    {% endblock content %}
    {% block js %} 
    <script src="{% static 'js/core/jquery.3.2.1.min.js' %}"></script>
    <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
    <script>
        $(document).on('submit', '#post-form',function(e){
            e.preventDefault();
            $.ajax({
                type:'POST',
                url:'{% url "feature_nathan:create" %}',
                data:{
                    title:$('#title').val(),
                    bahan:$('#bahan').val(),
                    alat:$('#alat').val(),
                    langkah:$('#langkah').val(),
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success:function(json){
                    document.getElementById("post-form").reset();
                    $(".posts").prepend('<div class="col-md-6">'+
                        '<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">' +
                            '<div class="col p-4 d-flex flex-column position-static">' +
                                '<h3 class="mb-0">' + json.title + '</h3>' +
                                '<p class="mb-auto">' + json.bahan + '</p>' +
                                '<p class="mb-auto">' + json.alat + '</p>' +
                                '<p class="mb-auto">' + json.langkah + '</p>' +
                            '</div>' +
                        '</div>' +
                    '</div>' 
                    )
                },
                error : function(xhr,errmsg,err) {
                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
            });
        });
    </script>
    {% endblock js %}
<!-- </html> -->