corona_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingPage.urls')),
    path('music/', include('feature_dion.urls')),
    path('movies/', include('feature_ajah.urls', namespace="movies")),
    path('health/', include('feature_nathan.urls')),
    path('events/', include('feature_aaya.urls', namespace="events")),
    path('activities/', include('feature_mirsa.urls')),
]

feature_mirsa/urls.py
from django.urls import path
from . import views

app_name = 'feature_mirsa'

urlpatterns = [
    path('', views.activities, name='activities'),
    path('tambah/', views.tambah_story, name='tambah_story'),
    path('list_story/', views.story, name='story'),
    # dilanjutkan ...
]

feature_mirsa/models.py
from django.db import models

# Create your models here.

class Story(models.Model):
    name = models.CharField(max_length=120, verbose_name="Your name")
    experience = models.TextField(blank=True, verbose_name="Your Experience!")

    def __str__(self):
        return self.name

feature_mirsa/forms.py
from django.forms import ModelForm
from .models import Story

class StoryForm(ModelForm):
	required_css_class = 'required'
	class Meta:
		model = Story
		fields = '__all__'

feature_mirsa/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import StoryForm
from .models import Story
# import loginrequired
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import requests
import json

# Create your views here.
@login_required(login_url="landingPage:signin")
def activities(request):
    return render(request, 'activities.html')


@login_required(login_url="landingPage:signin")
def story(request):
    if request.method == "POST":
        Story.objects.get(id=request.POST['id']).delete()
        return redirect('/activities/list_story/')
    cerita = Story.objects.all()
    context = {'list_story':cerita}
    return render(request, 'list_story.html', context)


@login_required(login_url="landingPage:signin")
def tambah_story(request):
    submit = False
    if request.method == 'POST':
        form = StoryForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/activities/tambah/?submit=True')
    else:
        form = StoryForm
        if 'submit' in request.GET:
            submit = True
    context = {'form': form, 'submit': submit}
    return render(request, 'story.html', context)

feature_mirsa/templates/activities.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <script src="{% static 'mirsa_js/activities.js' %}"></script>
    
{% endblock script %}

{% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mirsa_css/mirsa.css' %}" type="text/css">
{% endblock css %}

{% block title %} Now What | Activities {% endblock %}

{% block content %}

<section id="judul" class="container d-flex ">
    <div class="header row ">
        <div class="header-image col justify-content-center">
            <img src="{% static 'mirsa_img/children-drawing-playing-carpet.jpg' %}" class="img" alt="activities" style="border-radius: 65px; width: 100%;justify-content: center;"/>
        </div>
        <div class="header-description col" style="padding-left: 20px; padding-top: 20px;">
            <div class="desc-title">ACTIVITIES</div>
            <p style="text-align: justify; justify-content: center;">
                Tahun 2020 ini menjadi kejutan bagi banyak orang. 
                Tahun yang seharusnya diisi dengan berbagai rencana dan banyak aktvitas 
                namun dengan adanya pandemi ini hampir semuanya gagal. Namun ternyata 
                masih terdapat beberapa hal yang bisa kita lakukan di rumah untuk 
                mengganti rencana yang telah kita buat.
            </p>
        </div>
    </div>
</section>

<section id="listActivities" class="container-fluid d-flex flex-wrap align-content-center justify-content-center">
    <div class="judul section-title mx-auto"> 
        LITTLE THINGS YOU CAN DO IN QUARANTINE
    </div>
    <div class="box row justify-content-center align-content-center align-items-center">
        
        <div class="align-items-center justify-content-center" style="margin-left: 20px; margin-right: 20px;">
                <div>
                    <a href="#gardening"  class="kotak justify-content-center">
                        <span class="iconify" data-inline="false" data-icon="cil:plant" style="color: black; font-size: 150px;"></span>
                    </a>
                </div>
                <br>
                <h4>GARDENING</h4>
        </div>
        <div class="align-items-center justify-content-center" style="margin-left: 20px; margin-right: 20px;">
                <div>
                    <a href="#painting"  class="kotak justify-content-center">
                    <span class="iconify" data-inline="false" data-icon="whh:painting" style="color: black; font-size: 150px;"></span>
                    </a>
                </div>
                <br>
            <h4>PAINTING</h4>
        </div>
        <div class="align-items-center justify-content-center" style="margin-left: 20px; margin-right: 20px;">
            <div>
                 <a href="#cooking"  class="kotak justify-content-center">
                    <span class="iconify" data-inline="false" data-icon="mdi:chef-hat" style="color: black; font-size: 150px; justify-content: center;"></span>
                 </a>
            </div>
            <br>
            <h4>COOKING</h4>
        </div>
        <div class="align-items-center justify-content-center" style="margin-left: 20px; margin-right: 20px;">
            <div>
                 <a href="#workout"  class="kotak justify-content-center">
                    <span class="iconify" data-inline="false" data-icon="ic:baseline-sports-soccer" style="color: black; font-size: 150px;"></span>
                 </a>
            </div>
            <br>
            <h4>WORKOUT</h4>
        </div>
        <div class="align-items-center justify-content-center" style="margin-left: 20px; margin-right: 20px;">
            <div>
                 <a href="#reading"  class="kotak justify-content-center">
                    <span class="iconify" data-inline="false" data-icon="bx:bx-book-reader" style="color: black; font-size: 150px;"></span>
                 </a>
            </div>
            <br>
            <h4>READING</h4>
        </div>
    </div>
</section>



<div class="col detail container-fluid d-flex flex-wrap align-content-center justify-content-center">


<section id="gardening" class="set container-fluid d-flex flex-wrap align-content-center justify-content-center">
        <a class="bar section-title mx-auto">
            GARDENING
        </a>
    <div class="content row align-items-center justify-content-center">
        
        <div class="col-sm-5 mr-2">
            <img class="garden" src="{% static 'mirsa_img/PLANT.jpg' %}" alt="garden" data-aos="flip-left" data-aos-duration="1500">
            <article class="text-justify">
                <b>Berkebun</b> secara teratur terbukti baik untuk diri kita. Mulai dari manfaat terkait kesehatan yang membantu mengurangi risiko serangan jantung hingga membantu kita rileks setelah hari yang melelahkan. Pasti sangat mengasyikkan menjadi bugar dan mempertahankan gaya hidup sehat sambil berkebun.    
            <br>
            </article>
        </div>
        
        <div class="col-sm-5 mr-3" style="padding-left: 30px;">
            <div class="row" >
                <b>STEP TO START GARDENING</b>
                <ol>
                <li>Pilih tanaman apa yang ingin Anda tanam</li>
                <li>Pilih lokasi.</li>
                <li>Siapkan peralatan dasar untuk berkebun.</li>
                <li>Sediakan media tanam.</li>
                <li>Pilih benih tanam yang tepat.</li>
                <li>Tanam dengan hati-hati.</li>
                <li>Rawatlah dengan teratur.</li>
                </ol>
            </div>
            <div class="row-sm-4">
                <b> Untuk info lebih lanjut anda dapat mengunjungi beberapa situs di bawah ini:</b>
                <ul>
                    <li><a href="https://growinginthegarden.com/gardening-for-beginners-how-to-start-a-garden-in-8-simple-steps/" style="color:black;">How to Start a Garden in 8 Simple Steps</a></li>
                    <li><a href="https://mommiesdaily.com/2019/04/18/bercocok-tanam-101-untuk-pemula/" style="color:black;">Bercocok Tanam 101 untuk Pemula</a></li>
                </ul>
            </div>
        </div>
    </div>
</section> 

<section id="painting" class="set container-fluid d-flex flex-wrap align-content-center justify-content-center">
    <a class="bar section-title mx-auto">
        PAINTING
    </a>
    <div class="content row align-items-center justify-content-center">
        <div class="col-sm-5 mr-3">
            <div class="row">
                <b>STEP TO START PAINTING</b>
                <br>
                <ol>
                <li>Memahami unsur lukisan</li>
                <li>Memilih media lukis</li>
                <li>Pilih alat melukis yang sesuai</li>
                <li>Membuat gradasi warna</li>
                <li>Menambahkan detail pada lukisan</li>
                </ol>
            </div>
            <div class="row-sm-4">
                <b>Untuk info lebih lanjut anda dapat mengunjungi pranala di bawah ini:</b>
                <ul>
                    <li><a href="https://taupedia.com/bacaan/cara-melukis" style="color:black;">Cara Melukis</a></li>
                </ul>
            </div>
        </div>
           
        <div class="col-sm-5 mr-2">
            <img class="paint" src="{% static 'mirsa_img/PAINT.jpg' %}" alt="paint" data-aos="flip-left" data-aos-duration="1500">
            <article class="text-justify">
                <b>Melukis</b> bisa menjadi salah satu kegiatan untuk meluapkan kreativitas dalam diri. Menyenangkan untuk dilakukan, melukis pun kini jadi tren di kalangan anak muda untuk mengisi waktu luang di tengah pandemi virus Corona.
                <br>
            </article>
        </div>
    </div>
</section> 

<section id="cooking" class="set container-fluid d-flex flex-wrap align-content-center justify-content-center">
    <a class="bar section-title mx-auto">
        COOKING
    </a>
    <div class="content row align-items-center justify-content-center">
        <div class="col-sm-5 mr-2">
            <img class="cook" src="{% static 'mirsa_img/COOK.jpg' %}" alt="cook" data-aos="flip-left" data-aos-duration="1500">
            <article class="text-justify">
                <b>Memasak</b> merupakan salah satu aktivitas yang dapat kita lakukan di rumah saat pandemi seperti ini. Selain menyenangkan, memasak juga dapat meningkatkan kreativitas
            <br>
            </article>
        </div>
        
        <div class="col-sm-5 mr-3">
            <div class="row">
                <b>BENEFITS OF COOKING AT HOME</b>
                <ol>
                <li>Memasak memberikan kepuasan tersendiri (self-rewarding)</li>
                <li>Memasak bisa menghemat biaya</li>
                <li>Memasak mengurangi kecemasan atas higienitas di masa pandemi</li>
                </ol>
            </div>
            <div class="row-sm-4">
                <b>Untuk melihat referensi berbagai resep masakan, Anda dapat mengunjungi pranala berikut:</b>
                <ul>
                    <li><a href="https://cookpad.com/id" style="color:black;">Resep Cookpad</a></li>
                    <li><a href="https://www.royco.co.id/Ide-Resep.html" style="color:black;">Ide Resep</a></li>
                    <li><a href="https://www.masakapahariini.com/resep-masakan/" style="color:black;">Resep Masakan</a></li>
                </ul>
            </div>
           
        </div>
    </div>
</section>

<section id="workout" class="set container-fluid d-flex flex-wrap align-content-center justify-content-center">
    <a class="bar section-title mx-auto">
        WORKOUT
    </a>
    <div class="row align-items-center justify-content-center content">
        <div class="col-sm-5 mr-3">
            <div class="row-sm-3">
                <b>THE 6 BEST AT-HOME WORKOUTS</b>
                <ol>
                <li>Senam</li>
                <li>Zumba</li>
                <li>Jogging</li>
                <li>Sit Up</li>
                <li>Push Up</li>
                <li>Squat</li>
                </ol>
            
            </div>
            <div class="row-sm-4">
                <b>Untuk info lebih lanjut anda dapat mengunjungi pranala di bawah ini:</b>
                <ul >
                    <li><a href="https://www.nerdfitness.com/blog/the-7-best-at-home-workout-routines-the-ultimate-guide-for-training-without-a-gym/" style="color:black;">The Ultimate Guide for Training Without a Gym</a></li>
                </ul>
            </div>
        </div>
           
            <div class="col-sm-5 mr-3">
                <img class="workout" src="{% static 'mirsa_img/WORKOUT.jpg' %}" alt="paint" data-aos="flip-left" data-aos-duration="1500">
                <article class="text-justify">
                    <b>Olahraga</b> merupakan salah satu cara efektif untuk tetap produktif di kala pandemi. Selain menyehatkan, olahraga juga dapat mencegah stress. Meskipun kita tidak bisa berolahraga secara bebas di luar rumah, banyak olahraga yang bisa kita lakukan di rumah.<br>
                </article>
            </div>
    </div>
    <br>
</section>


<section id="reading" class="set container-fluid d-flex flex-wrap align-content-center justify-content-center">
    <a class="bar section-title mx-auto">
        READING
    </a>
<div class="content row align-items-center justify-content-center">
    
    <div class="col-sm-5 mr-2">
        <img class="read" src="{% static 'mirsa_img/READ.jpg' %}" alt="read" data-aos="flip-left" data-aos-duration="1500">
        <article class="text-justify">
            <b>Membaca</b> merupakan salah satu kegiatan yang dapat kita lakukan untuk mengisi waktu luang di saat pandemi seperti ini. Banyak sekali buku yang dapat kita jadikan sumber bacaan yang tentunya dapat menambah pengetahuan kita.
        <br>
        </article>
    </div>
    
    <div class="col-sm-5 mr-3" style="padding-left: 30px;">
        <div class="row" >
            <b>BENEFIT OF READING</b>
            <ul>
            <li>Meningkatkan Daya Ingat.</li>
            <li>Meningkatkan Kemampuan Konsentrasi.</li>
            <li>Menurunkan Risiko Stres dan Depresi.</li>
            <li>Meningkatkan Kemampuan Komunikasi.</li>
            </ul>
        </div>
    </div>
    <div class="row-sm-4">
        <br>
        <b style="text-align: center;"> Silahkan cari buku yang ingin dibaca:</b>
        <input id="keyword"  style ="margin-top: 40px;" placeholder="Input the book's title">
        <ol id="daftarBuku">
        </ol>
    </div>
</div>
</section> 



<section class="container-fluid d-flex flex-wrap align-content-center justify-content-center" style="margin-top: 50px;">
    <button class="buttonStory" style="margin-bottom:50px;">
    <a href="{% url 'feature_mirsa:tambah_story' %}" class="text-white">
        Share Your Story!
    </a>
    </button> 
</section>


</div>



{% endblock content %}

feature_mirsa/templates/list_story.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
{% endblock script %}

{% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mirsa_css/activities.css' %}" type="text/css">
{% endblock %}

{% block title %} Now What | Activities {% endblock %}

{% block content %}

<section class="container-fluid d-flex flex-wrap ">
    <div>
    
    </div>
    
    <div class="container-fluid">
      <div class="section-title mx-auto text-center p-5"> 
        OTHER EXPERIENCE
      </div>
      
      <!-- <div class="section-title"> 
        <h3 >Others Experience</h3>
      </div> -->
      
      {% for i in list_story %}
        <div class="card w-100">
          <div class="card-body">
            <h5 class="card-title">{{ i.name }}</h5>
            <p class="card-text">{{ i.experience }}</p>
            <div class="d-flex flex-row">
              <form method="POST" action="{% url 'feature_mirsa:story' %}">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ i.id }}">
                <button type="submit" value="Submit" class="card-link btn btn-danger">Delete</button>
              </form>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
    <button class="button" style="margin-top:40px;">  
        <a href="{% url 'feature_mirsa:activities' %}" class="text-white">
          Back to Activities
        </a>
    </button>
    </section>

{% endblock %}

feature_mirsa/templates/story.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mirsa_css/mirsa.css' %}" type="text/css">
{% endblock %}

{% block title %} Now What | Activities {% endblock %}

{% block content %}

<section class="container d-flex flex-wrap align-content-center justify-content-center">
    {% if submit%}
    
        <div class="mx-auto text-center p-5">
          <div class="section-title mx-auto text-center p-5"> 
            THANKS FOR SHARING WITH US! :)
        </div>
          <br>
          <button class="button"> 
          <a href="{% url 'feature_mirsa:activities' %}" class="text-white">
            Back to Activities
          </a>
          </button>
          <br>
          <button class="button" style="margin-top: 40px;"> 
            <a href="{% url 'feature_mirsa:story' %}" class="text-white">
              See others experience
            </a>
            </button>
        </div> 
    
    {% else %}
        <div class="pertanyaan container">
            <div class="section-title mx-auto text-center p-5 justify-content-center"> 
                SHARE YOUR EXPERIENCE DOING AN ACTIVITIES AT HOME
            </div>
    
            <form  action="" method="post" novalidate>
                {% csrf_token %}
                <!-- <p  style="text-align: center;color: #0a5687; font-weight: bold;">{{ user.username }}</p> -->
                
                <div class="form-group" style="text-align: center;">
                    <p  style="text-align: center;color: #0a5687; font-weight: bold;">Your Name</p>
                  {{ form.name }}
                </div>
                <div class="form-group"  style="text-align: center; margin-top: 40px;">
                    <p  style="text-align: center;color: #0a5687; font-weight: bold;">Your Experience!</p>
                  {{ form.experience }}
                </div>
                <div class="form-group"  style="text-align: center;">
                  <input type="submit" value="Share" class="button" style="text-align: center; ">
                </div>
                
              </form>
        </div>
        
 
        
    {% endif %}
    
    </section> 
    

{% endblock %}