corona_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingPage.urls')),
    path('music/', include('feature_dion.urls')),
    path('movies/', include('feature_ajah.urls', namespace="movies")),
    path('health/', include('feature_nathan.urls')),
    path('events/', include('feature_aaya.urls', namespace="events")),
    path('activities/', include('feature_mirsa.urls')),
]

feature_aaya/urls.py
# from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'feature_aaya'
urlpatterns = [
    url(r'^$', views.events, name='events'),  
    url(r'^preform/$', views.preform, name='preform'),   
]

feature_ajah/urls.py
from django.urls import path
from . import views

app_name = 'feature_ajah'
urlpatterns = [
    path('', views.movies, name="movies"),
    path('listForm/', views.listForm, name="listForm"),
    path('forms/', views.forms, name="forms"),
    path('data', views.fungsi_data, name='data'),

]

feature_dion/urls.py
from django.urls import path
from . import views

app_name = 'feature_dion'
urlpatterns = [
    path('', views.index, name="music"),
    path('share/<int:id_>/', views.share, name="share")
]

landingPage/urls.py
from django.urls import path
from . import views

app_name = 'landingPage'
urlpatterns = [
    path('', views.index, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="icon" type="image/png" href="{% static 'landing_images/LOGO_ICON.png' %}">
    {% block script %}
    {% endblock script %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'landing_css/base.css' %}" />
    <title>
        {% block title %} {% endblock title %}
    </title>
    {% block css %}
    {% endblock css %}
</head>

<body>
    <div id="try-two" class="try-two">
        <div class="try-button">
            <img class="close" onclick="closeNav()" src="{% static 'landing_images/160171083747624487.png'%}"
                width="30px" height="30px" />
        </div>
        {% if user.is_authenticated %}
        <div class="pop-menu-container">
            <a class="pop-menu" onclick="closeNav()" id="usrname2">{{user.username}}</a>
            <a id="about2" class="pop-menu" href="#nowhat" onclick="closeNav()">About</a>
            <a href="{% url 'feature_dion:music' %}" class="pop-menu" onclick="closeNav()" id="music2">Music</a>
            <a href="{% url 'feature_ajah:movies' %}" class="pop-menu" onclick="closeNav()" id="movies2">Movies</a>
            <a href="{% url 'feature_aaya:events' %}" class="pop-menu" onclick="closeNav()" id="events2">Events</a>
            <a href="{% url 'feature_nathan:index' %}" class="pop-menu" onclick="closeNav()" id="health2">Health</a>
            <a href="{% url 'feature_mirsa:activities' %}" class="pop-menu" onclick="closeNav()"
                id="activites2">Activities</a>
            <a href="{% url 'landingPage:signout'%}" class="pop-menu" onclick="closeNav()" id="signout2">Sign Out</a>
        </div>
        {% else %}
        <div class="pop-menu-container">
            <a id="about3" class="pop-menu" href="#nowhat" onclick="closeNav()">About</a>
            <a href="{% url 'landingPage:signup'%}" class="pop-menu" onclick="closeNav()" id="signin2">Sign Up</a>
            <a href="{% url 'landingPage:signin'%}" class="pop-menu" onclick="closeNav()" id="signin2">Sign In</a>
        </div>
        {% endif %}
    </div>
    <div class="nav-container">
        <div class="navbar">
            <div class="now-what-title">
                <a id="left-title" href="{% url 'landingPage:home' %}">NoWhat?</a>
            </div>
            <div class="nav-menu">
                {% if user.is_authenticated %}
                <div class="tryone">
                    <a id="usrname" class="menu trybtn" href="#" style="text-transform:capitalize" onclick="dropdown()">
                        {{user.username}}<img style="width: 0.75rem; margin-left: 0.25rem"
                            src="{% static 'landing_images/Vector.png' %}" />
                    </a>
                    <div class="tryone-content">
                        <a id="signout" class="drop" href="{% url 'landingPage:signout'%}">Sign Out</a>
                    </div>
                </div>
                <a id="about" class="menu" href="#nowhat" onclick="about()">About</a>
                <div class="tryone">
                    <a id="browse" class="menu trybtn" href="#" onclick="dropdown()">Browse
                        <img style="width: 0.75rem;" src="{% static 'landing_images/Vector.png' %}" />
                    </a>
                    <div id="toshow" class="tryone-content">
                        <a class="drop" id="music" href="{% url 'feature_dion:music' %}">Music</a>
                        <a class="drop" id="movies" href="{% url 'feature_ajah:movies' %}"> Movies</a>
                        <a class="drop" id="events" href="{% url 'feature_aaya:events' %}"> Event</a>
                        <a class="drop" id="health" href="{% url 'feature_nathan:index' %}"> Health</a>
                        <a class="drop" id="activites" href="{% url 'feature_mirsa:activities' %}"> Activities</a>
                    </div>
                </div>
                {% else %}
                <a id="signin" class="menu" href="{% url 'landingPage:signin'%}">Sign In</a>
                <a class="menu">|</a>
                <a id="signin" class="menu" href="{% url 'landingPage:signup'%}">Sign Up</a>
                <a id="about" class="menu" href="#nowhat" onclick="about()">About</a>
                {% endif %}
            </div>
            <div onclick="openNav()" class="burgerButton">
                <img class="burgerButton" src="{% static 'landing_images/burgerButton.png' %}" alt="menu" />
            </div>
        </div>
    </div>
    <div class="main-container">
        {% block content %} {% endblock content %}
    </div>
    {% block js %} {% endblock js %}
    <script src="{% static 'landing_js/base.js' %}"></script>
    <div id=nowhat></div>
    <footer id="aboutus">
        <div class="foot-cont">
            <div class="cont">
                <div class="about-nowhat">
                    <div class="about">
                        <div class="about-title">
                            ABOUT NOWHAT
                        </div>
                        <div class="description">

                            Dengan banyaknya pilihan dan referensi kegiatan,
                            <b>NoWhat?</b> dibuat dengan harapan dapat membuat
                            masyarakat tetap merasakan kesenangan
                            ditengah pandemi ini.

                        </div>
                    </div>
                    <img class="logo" src="{% static 'landing_images/LOGO.png' %}" alt="LOGO" />
                </div>
            </div>
            <div class="copyrights">
                <div class="text">
                    © Nowhat? 2020
                </div>
                <img class="small-logo" src="{% static 'landing_images/LOGO.png' %}" alt="LOGO" />
                <div class="text right">
                    All Rights Reserved.
                </div>
            </div>
        </div>
    </footer>
</body>


</html>